# Generated by Django 4.0 on 2022-01-15 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BeEventful', '0003_u'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='U',
            new_name='User1',
        ),
    ]
