# Generated by Django 4.0 on 2022-01-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeEventful', '0004_rename_u_user1'),
    ]

    operations = [
        migrations.AddField(
            model_name='user1',
            name='Address',
            field=models.TextField(default='shyam villa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user1',
            name='Email',
            field=models.EmailField(default='sm@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user1',
            name='Gender',
            field=models.CharField(default='female', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user1',
            name='Password',
            field=models.CharField(default='1234', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user1',
            name='Phone_No',
            field=models.IntegerField(default=1234),
            preserve_default=False,
        ),
    ]
