# Generated by Django 4.0 on 2022-01-15 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BeEventful', '0005_user1_address_user1_email_user1_gender_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
