# Generated by Django 4.0 on 2022-01-15 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BeEventful', '0006_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User1',
            new_name='User',
        ),
    ]
