# Generated by Django 4.0 on 2022-01-15 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BeEventful', '0007_rename_user1_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone_No', models.IntegerField()),
                ('Address', models.TextField()),
                ('Gender', models.CharField(max_length=10)),
                ('Dob', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BeEventful.user')),
            ],
        ),
    ]
