# Generated by Django 4.0 on 2022-01-16 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BeEventful', '0009_alter_profile_user_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
